services:

  app:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/web
      - .env/database
    ports:
      - 3000:3000

  database:
    image: postgres:16.2
    env_file:
      - .env/database
    expose:
      - 5432  
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
